config/routes.rb
Rails.application.routes.draw do

  get 'new_vocab' => 'vocabs#new'
  post 'vocabs'=>'vocabs#create'

  get 'lessons/new'

  get 'new_grammar_point' => 'grammar_points#new'
  post 'grammar_points'=>'grammar_points#create'

  get 'chapters/index' 

  root 'main_pages#home'
  
  get 'about'      => 'main_pages#about'
  get 'contact'    => 'main_pages#contact'
  get 'landing'    => 'main_pages#landing'
  get 'donate'     => 'main_pages#donate'
  get 'study'      => 'main_pages#study'

  resources :chapters
  resources :lessons
  resources :vocab_lists

  devise_for :users

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :lessons
end

app/models/grammar_point.rb
class GrammarPoint < ActiveRecord::Base
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :chapter
  has_many :grammar_points
  has_many :vocab_lists
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vocab.rb
class Vocab < ActiveRecord::Base
  belongs_to :vocab_list

#en and #jp attributes, both=strings
#"formality" attribute????
#separate model for kanji
#references :vocab_list index: true
#foreign_key :vocab_list
end

app/models/vocab_list.rb
class VocabList < ActiveRecord::Base
	belongs_to :lesson
	#add belongs_to :user IF vocablist should be associated with individual user??? 
	#^^^thinking about implementing flash cards
	has_many :vocabs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
	#need to set filters... before_action ____

  def index					#list all chapters
  	#@chapters = Chapter.paginate(page: params[:page])
  	@chapters = Chapter.all
  end

  def show					#show a specific chapter
  	@chapter = Chapter.find(params[:id])
    #@lessons = @chapter.lessons.paginate(page: params[:page])
    @lessons = @chapter.lessons.all
  end
  #need to install a pagination gem

  def new 					#display chapter creation view
  	@chapter = Chapter.new
  end

  def create				#create chapter
  	@chapter = Chapter.new(chapter_params)
  	if @chapter.save
			flash[:success] = "Chapter created!"
			redirect_to @chapter
		else
			render 'new'
		end
  end

  def destroy				#delete chapter
		@chapter.destroy
		flash[:success] = "chapter deleted"
		redirect_to root_url
	end

  def edit   #display chapter edit view.... doesnt actually update it
    @chapter = Chapter.find(params[:id])
  end


  def update
  	#NEED TO WRITE THIS METHOD 
    @chapter = Chapter.find(params[:id])
      if @chapter.update_attributes(chapter_params)
        flash[:success] = "Profile updated"
        redirect_to @chapter
      else 
        render 'edit'
      end
  end


  private

		def chapter_params
			params.require(:chapter).permit(:name, :description)
		end
end

app/controllers/grammar_points_controller.rb
class GrammarPointsController < ApplicationController

	def new
		@grammar_point = GrammarPoint.new
	end

	def create
		@grammar_point = GrammarPoint.create!(grammar_point_params)
		if @grammar_point.save
      flash[:success] = "Grammar point created!"
      #redirect_to @vocab_list ---- should redirect to its own vocab list
      #but I don't know how to do it -chris
      redirect_to chapters_path
    else
      flash[:error] = "failed to save"
    end
	end

	def show
		@list = GrammarPoint.find(params[:id])
	end
# は is the topic marker particle. This means that は (pronounced "wa") can mark the subject of the sentence (the actor) or the subject being discussed.

# Example: 
# "I am a student." 
# 私は学生です。
	private

  	def grammar_point_params
  		params.require(:grammar_point).permit(:content, :lesson_id)
		end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

	def show					#show a specific lesson
  	  	@lesson = Lesson.find(params[:id])
        @vocab_lists = @lesson.vocab_lists.all
        @grammar_points = @lesson.grammar_points.all
  end

  def new 					#display lesson creation view
  	@lesson = Lesson.new
  	#@chapter = @lesson.chapter
  end

  def create
#... dont know how/ if possible to track the previous pages a user has been on... 
#possible temporary solution: select the chapter in a dropdown list...

  	#need to write a method to find the chapter of a lesson????????? not sure how to tie to each other
  	@lesson = Lesson.create!(lesson_params)
		if @lesson.save
			flash[:success] = "Lesson created!"
			redirect_to @lesson
		else
			flash[:error] = "failed to save"
		end
  end

  def destroy
  end

  def update
  end

  private

  	def lesson_params
  		params.require(:lesson).permit(:name, :chapter_id)
		end

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def landing
  end

  def contribute
  end

  def study
  end
end

app/controllers/vocab_lists_controller.rb
class VocabListsController < ApplicationController
	def new
		@vocab_list = VocabList.new
	end

	def create
		@vocab_list = VocabList.create!(vocablist_params)
		if @vocab_list.save
			flash[:success] = "List created!"
			redirect_to @vocab_list
		else
			flash[:error] = "failed to save"
		end
	end

	def show
		@list = VocabList.find(params[:id])
		@vocabs = @list.vocabs
	end

	private

  	def vocablist_params
  		params.require(:vocab_list).permit(:name, :lesson_id)
		end
		##### require that it be associated with a lesson??
end

app/controllers/vocabs_controller.rb
class VocabsController < ApplicationController
  def new
    @vocab = Vocab.new
  end

  def create
  	#need to be associated with a specific vocab_list. vocab_lists have IDs 
    #which are related to the order in which they are created, 
    #but unrelated to the lesson which they are connected to 
 		@vocab = Vocab.create!(vocab_params)
    if @vocab.save
      flash[:success] = "Vocab created!"
      #redirect_to @vocab_list ---- needs to redirect to its own vocab list...
      redirect_to chapters_path
    else
      flash[:error] = "failed to save"
    end
  end

  private

  	def vocab_params
  		params.require(:vocab).permit(:en, :jp, :vocab_list_id)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/grammar_points_helper.rb
module GrammarPointsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/vocab_lists_helper.rb
module VocabListsHelper
end

app/helpers/vocabs_helper.rb
module VocabsHelper
end

app/views/chapters/index.html.erb
<h1>Chapters</h1> 

<!-- what is a chapter?
a set of lessons, vocabulary and exercises with a common theme, level or grammar structures 
is there a better name for this? -->

<style>
	div.char_title {
		margin-bottom: 8px; color: black; text-decoration: none;		
	}
	div.char_desc {
		margin-left: 20px; display: block; color: #333; text-decoration: none;		
	}
</style>

<div class="chapters" style = "width: 100%;">
	<!-- was a ul containing li's -->
		<% @chapters.each do |chapter| %>
			<div class = "chapter" style = "width: 15%; background-color: #e6f8ff; display: inline-block">
				<!-- add an image on the side to represent the chapter -->
				<div class = "char_title">
					<%= link_to chapter.name, chapter, {style: "margin-bottom: 8px; color: black; text-decoration: none; width: 100%;"} %>
				</div>
				<!-- when chapters can be linked to profiles, add the author's name, information about whether it's editable by everyone, etc -->
				<div class = "char_desc">
					<%= link_to chapter.description, chapter, {style: "margin-left: 20px; display: block; color: #333; text-decoration: none; width: 100;"} %>
				</div>
			</div>
		<% end %>
</div>
</br>
<%= link_to "New Chapter", new_chapter_path %>

app/views/chapters/new.html.erb
<h1>Create a chapter</h1>

<div>
  <%= form_for(@chapter) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <!-- add an image that represents the chapter, to be displayed on the browse chapters page -->
	
    <%= f.submit "Save Chapter" %>
  <% end %>
</div>

app/views/chapters/show.html.erb
<h1><%= @chapter.name %></h1>

<%= render 'lessons/lessons' %>

<%= link_to "New Lesson", new_lesson_path %>

app/views/grammar_points/_grammar_points.html.erb
<ol class="grammarpoints">
		<% @grammar_points.each do |gp| %>
			<li>
				<%= gp.content %>
				<!-- shouldnt be a link, should display GP and vocab lists within
				lesson show page -->
			</li>
		<% end %>
</ol>

app/views/grammar_points/new.html.erb
<h1>Create a grammar point explanation</h1>

<div>
  <!-- submitting this form sends @grammar_point to the grammar_point controller create method -->
  <!-- @grammar_point = instance variable -->
  <!-- in rails forms: submit = HTTP post request --> 
  <%= form_for(@grammar_point) do |f| %> 

    <%= f.label :lesson_id %>
    <%= collection_select(:grammar_point, :lesson_id, Lesson.all, :id, :name, prompt: true) %>
    
    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.submit "Save Grammar Point" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="mt4 center bottom-0 border-top right block">

			<div class="footer center">
				<%= link_to "Chapters", chapters_path, :class => "button button-primary m1 bg-teal" %>
				<%= link_to "About", about_path, :class => "button button-primary m1 bg-teal" %>
				<%= link_to "Study", study_path, :class => "button button-primary m1 bg-teal" %>
				<%= link_to "Contact", contact_path, :class => "button button-primary m1 bg-teal" %>
			</div>
			
	</footer>
</div>

app/views/layouts/_header.html.erb
<header>
	<nav class="clearfix bg-aqua">
		<div class="container">

			<%= link_to "Speaksy", 	root_path, :class => "logo h2 caps left m1 bold " %>		

			<% if user_signed_in? %>
				<%= link_to "Log out", destroy_user_session_path, method: "delete", :class => "button button-transparent right m1" %>

			<% else %>
					<%= link_to "Log In", 	new_user_session_path, :class => "button button-transparent right m1" %>
					<%= link_to "Sign Up", 	new_user_registration_path, :class => "button button-primary right m1" %>
			<% end %>
			
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8"> 
	<!-- need to set dynamic titles -->
  <title>Speaksy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- header -->

<%= render 'layouts/header' %>

<!-- main content -->
<div class="container">
	<%= yield %>
</div>
<!-- footer -->

<%= render 'layouts/footer' %>

</body>
</html>

app/views/lessons/_lessons.html.erb
<ol class="lessons">
		<% @lessons.each do |lesson| %>
			<li>
				<%= link_to lesson.name, lesson %>
				<!-- NEED TO MAKE THIS INTO A LINK TO LESSON PAGE -->
			</li>
		<% end %>
</ol>

app/views/lessons/new.html.erb
<h1>Create a Lesson</h1>

<p>Need some way to create grammar points, vocab, etc...</p>

<div>
  <%= form_for(@lesson) do |f| %> 

	<!-- submitting this form sends @lesson to the lesson controller create method -->
  <!-- @lesson = instance variable -->
  <!-- in rails forms: submit = HTTP post request --> 

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :chapter_id %>
    <%= collection_select(:lesson, :chapter_id, Chapter.all, :id, :name, prompt: true) %>

    <%= f.submit "Save Lesson" %>
  <% end %>
</div>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>

<!-- show lessontext -->

<!-- show vocablist -->
<%= render 'vocab_lists/vocab_lists' %>

<%= link_to "New Vocab List", new_vocab_list_path %>

<!-- show grammar_points -->

<%= render 'grammar_points/grammar_points' %>

<%= link_to "New Grammar Point", new_grammar_point_path %>

<!-- show exercises -->

<br/><br/>

<!-- make one form for all lesson-based content?" -->

<%= link_to "Create New Content", '#' %>

app/views/main_pages/about.html.erb
<h1 class="center">About</h1>
<p class="center">ann arbors most chic hookah lounge can be found at 666 e washington</p>

app/views/main_pages/contact.html.erb
<div class="center">
	<h1>Contact Us</h1>
	<p>send us emails plz @ bing@speaksy.org</p>
</div>

app/views/main_pages/donate.html.erb
<div class="center">
	<h1>Please help us</h1>
	<p>If you are interested in assisting us with either your time or money, please contact us at philanthropy@tri.delt</p>
</div>

app/views/main_pages/home.html.erb
<div class="panorama center">
	<!-- <p>welcome to speaksy -0.0.0.1.1</p> -->
		<h1><br/><br/><a title="'Welcome!!' [he yookoso]" class="tooltip">へようこそ!!</a></h1>
	
</div>

app/views/main_pages/landing.html.erb
<!-- this should be integrated into the home page and served to new users or people not logged in -->

<h1 class="center">speaksy</h1>
<h2 class="center">language learning democratized</h2> 
<!-- credit to yesid for this phrase 
			it would appeal to a niche hxc language learning audience but few others-->
<p>mission statement</p>

app/views/main_pages/study.html.erb
<!-- <div class="center">
	<h1 class="h1 bold">
		Lesson 0 - 
		<a href="#" class="tooltip">へようこそ!!
			<span>
				Welcome!! [he yookoso]
			</span>
		</a>
	</h1>
	<p>This is where it all begins. Your 
		<a href="#" class="tooltip">りょこう
			<span>
				journey, trip [ryokoo]
			</span>
		</a> 

			to success in the world of 
			
		<a href="#" class="tooltip">日本語
			<span>
				Japanese language [nihongo]
			</span>
		</a>

			starts now!
		</p>
</div> -->

<div class="center">
	<h1 class="h1 bold">
		Lesson 0 - 
		<a title="'Welcome!!' [he yookoso]" class="tooltip">へようこそ!!</a>
	</h1>
	<p>This is where it all begins. Your 
		<a title="'journey, trip' [ryokoo]" class="tooltip">りょこう</a> 

			to success in the world of 
			
			<a title="'Japanese' [nihongo]" class="tooltip">日本語</a>

			starts now!
		</p>
</div>

<!-- <div class="center">
	<h1 class="h1 bold">
		Lesson 0 - 
		<span id="poppa">へようこそ</span>
	</h1>

	<span id="popped" class="popped" style="display: none">"Welcome", or /e/ /youkoso</span>
</div>


<script type="text/javascript">
var e = document.getElementById('poppa');
e.onmouseover = function() {
  document.getElementById('popped').style.display = 'block';
}
e.onmouseout = function() {
  document.getElementById('popped').style.display = 'none';
}
</script> -->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/vocab_lists/_vocab_lists.html.erb
<ol class="vocablists">
		<% @vocab_lists.each do |vl| %>
			<li>
				<%= link_to vl.name, vl %>
				<!-- shouldnt be a link, should display vocabs from this vocab list
				on lesson show page -->
			</li>
		<% end %>
</ol>

app/views/vocab_lists/new.html.erb
<h1>Create a list of vocab words</h1>

<div>
  <%= form_for(@vocab_list) do |f| %> 

	<!-- submitting this form sends @vocab_list to the vocab_list controller create method -->
  <!-- @vocab_list = instance variable -->
  <!-- in rails forms: submit = HTTP post request --> 

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :lesson_id %>
    <%= collection_select(:vocab_list, :lesson_id, Lesson.all, :id, :name, prompt: true) %>

    <%= f.submit "Save List" %>
  <% end %>
</div>

app/views/vocab_lists/show.html.erb
<h1><%= @list.name %></h1>

<%= render 'vocabs/vocabs' %>

<%= link_to "New Vocab", new_vocab_path %>
<!-- new_vocab_path -->

app/views/vocabs/_vocabs.html.erb
<ul class="vocabs">
		<% @vocabs.each do |vk| %>
			<li>
				<%= vk.jp + " means " + vk.en %>
			</li>
		<% end %>
</ul>

app/views/vocabs/new.html.erb
<h1>Add a vocab word</h1>

<div>
  <!-- submitting this form sends @vocab to the vocab controller create method -->
  <!-- @vocab_list = instance variable -->
  <!-- in rails forms: submit = HTTP post request -->

  <%= form_for(@vocab) do |f| %> 

    <%= f.label :en %>
    <%= f.text_field :en %>

    <%= f.label :jp %>
    <%= f.text_field :jp %>

    <%= f.label :vocab_list_id %>
    <%= collection_select(:vocab, :vocab_list_id, VocabList.all, :id, :name, prompt: true) %>

    <%= f.submit "Add vocab word" %>
  <% end %>
</div>